### ISSUE TITLE
Only first element of a gRPC server stream is transmitted in QueryServer_Event_Fire.vi

### ISSUE THREAD

**Issue by nprorekhin** [ni/grpc-labview#1]
Hi,

I've discovered one thing when working with the example. 

It seems like _example\VIs\QueryServer_Event_Fire.vi_ transmits only the first element, however it is a gRPC stream and we should see different messages arriving to the client.

Steps to reproduce:
1. Modify the shipping example ExampleQueryServer.vi. Open Timeout case and add some dynamic information to the "Hear Beat" message. I did it with server uptime.
![gRPC-stream](https://user-images.githubusercontent.com/53332180/104469770-2a2f8480-55b9-11eb-920e-3c10289b7658.png)
2. Start _example_client.exe_
3. We do receive 10 stream messages but they are the same:
```
Server uptime: 15.393039
Server Event: Heart Beat, uptime 16.397 seconds
Server Event: Heart Beat, uptime 16.397 seconds
Server Event: Heart Beat, uptime 16.397 seconds
Server Event: Heart Beat, uptime 16.397 seconds
Server Event: Heart Beat, uptime 16.397 seconds
Server Event: Heart Beat, uptime 16.397 seconds
Server Event: Heart Beat, uptime 16.397 seconds
Server Event: Heart Beat, uptime 16.397 seconds
Server Event: Heart Beat, uptime 16.397 seconds
Server Event: Heart Beat, uptime 16.397 seconds
Server notifications complete
```

Am I missing something or is gRPC server streaming is not yet fully implemented?

**Comment by ccifra** [comment]
Fixed with 58e404ab8ed0578b47eebe31acef6613cc10676a.
