### ISSUE TITLE
Linux RT creates multiple listening socket for the same port

### ISSUE THREAD

**Issue by abahetik** [ni/grpc-labview#112]
I noticed a couple of problem when running grpc-labview server on an RT machine. 
 
1. The first time you run the server it runs properly but when you try to stop the server it does not work.
2. If you relaunch the server on the same port it creates another socket for the same port for listening. Due to which the client request get lost (probably because there are multiple sockets open). Attached netstat for the RT machine.
![image](https://user-images.githubusercontent.com/64770378/185092034-380fea05-37aa-45c6-8180-df093b79a7f4.png)

This same behavior is not seen in Windows. 

Windows behavior is:
1. It kills the listening port when you stop the server.

**Comment by olfenr** [comment]
Some ideas :
- Close function is not called.
- If the close function is the LabVIEW one, it never closed instantly a tcp connection...
- ... but a non-effective port can be reopened if the SO_REUSEADDR option is applied during this time.
- If the close function is a Linux system call, a default behavior can be applied by the kernel.
- The default behavior of Linux when closing a tcp port is to keep it unopenable during 60s with. But in that case the CLOSED flag or the TIME_WAIT flag is shown and the next connection cannot be opened, which is not the case here.

Conclusion : could it be an asynchrone issue between close and open while the SO_REUSEADDR option is used ?

**Comment by abahetik** [comment]
#114 has resolved this issue. I am closing this
