### ISSUE TITLE
[v0.4.8.2] Wrong name of lvsupport lvlib in the grpc_library vip file (gprc -> grpc)

### ISSUE THREAD

**Issue by olfenr** [ni/grpc-labview#113]
An error is issued in the code generator tool while trying generating server and client after modifying the proto (the tools searches for a "gprc-lvsupport-release.lvlib").

Just rename the source like this resolves the issue :
![image](https://user-images.githubusercontent.com/12133231/185104723-24934f01-9885-4607-832a-ef42447d6f60.png)

**Comment by cq-fm** [comment]
which file is this? i can not find a"Get grpc-library-ref" VI?

**Comment by eyesonvis** [comment]
The file is <labview>\vi.lib\gRPC\gRPC Server and Client Template [2]\gRPC Scripting Tools\Library API\Get grpc-library ref.vi and the error is that the r and p are transposed in "g**rp**c-lvsupport-release" in the string constant.

**Comment by eyesonvis** [comment]
This was fixed in source, but not yet in the release package: https://github.com/ni/grpc-labview/pull/109

**Comment by cq-fm** [comment]
got it, thank you
