### ISSUE TITLE
Simulateours client stream reads can hang or crash

### ISSUE THREAD

**Issue by NIbbuchanan** [ni/grpc-labview#117]
There are hangs/crashes when simultaneous client stream reads happen. See the attached example that illustrates the problem.
[gRPC Hang and Crash with Simultaneous Reads.zip](https://github.com/ni/grpc-labview/files/9394997/gRPC.Hang.and.Crash.with.Simultaneous.Reads.zip)

**Comment by NIbbuchanan** [comment]
I was able to build with MSVC 2019 compiler and didn't have this problem. We should consider documenting that 2019 is the recommended compiler.

**Comment by ni-sujain** [comment]
I have updated the building instructions here  
https://github.com/ni/grpc-labview/commit/17cc32a61ce521f0dd05287740ae8fda0f4472e7
