### ISSUE TITLE
Packing and unpacking data in 64 bit grpc-labview sometimes loses data

### ISSUE THREAD

**Issue by shivaprasad-basavaraj** [ni/grpc-labview#119]
Packing and unpacking data is sometimes lossy. In the attached example, we are packing and unpacking data and some data is lost as seen in the image below. This happens only with the 64-bit version.

![image](https://user-images.githubusercontent.com/35128660/186388734-3c6fed6e-f417-4318-9b35-24a4963eed23.png)

*Steps to reproduce*
- Extract the attached 'proto parsing.zip' and open 'proto debug.lvproj'
- Open the SimplestPackUnpack.vi and run it
- Observe that we lose data as shown in the image

_The project is saved in LV 2021_

[proto parsing.zip](https://github.com/ni/grpc-labview/files/9414990/proto.parsing.zip)
.

**Comment by gregr-ni** [comment]
We are computing the wrong size for the first 2 clusters in UpdateMetadataClusterLayout. We're padding them to 8 bytes which would be correct if they contained any 8 byte values but they don't. Clusters are only padded to the max size of their elements. Specifically the [AlignClusterOffset ](https://github.com/ni/grpc-labview/blob/f402ef2dbbdad8321cbe0bd0079934782063fabe/src/message_element_metadata_owner.cc#L153)used to assign the clusterSize is wrong. It can't use a fixed type (currently StringValue). It should use the type of the largest element and false for "repeated".

This also means that we are copying 8 bytes beyond the end of the cluster into the message when packing and overwriting 8 bytes beyond the cluster when unpacking.

**Comment by shivaprasad-basavaraj** [comment]
Fixed in release 0.4.8.4.
