### ISSUE TITLE
"Servicer.lvclass:Start Server.vi" returns error 1097 when proto file contains "Empty" message

### ISSUE THREAD

**Issue by gaoruhao** [ni/grpc-labview#129]
"Servicer.lvclass:Start Server.vi" returns error 1097 when proto file contains "Empty" message.
![image](https://user-images.githubusercontent.com/6160645/187607095-f88aa2fc-fa03-4cf9-8de4-b969c6204f4d.png)

Steps to reproduce:
1. Generate the test project with the following proto file:
```proto
syntax = "proto3";

package adas;

service TestService {
  rpc Funtion1 (Empty) returns (Empty) {}
  rpc Funtion2 (Empty) returns (Empty) {}
}

message Empty {
}
```

2. Execute "Run Service.vi" in the server lib and you will get an error 1097.
![image](https://user-images.githubusercontent.com/6160645/187607455-d45743b7-a397-4d8c-9330-ebf4bdaec0e9.png)

**Comment by shivaprasad-basavaraj** [comment]
This issue has been fixed in the #134 and has been picked up by the 0.4.9.1 release.
