### ISSUE TITLE
Error 7 when generating gRPC code or running gRPC communication on Win

### ISSUE THREAD

**Issue by yijueli** [ni/grpc-labview#168]
Version: 0.5.0.2
Encountered error 7 in the two cases below.
When l tried to use Code Generator to generate client code according to the example proto: helloworld. proto, the error 7 occured.
![image](https://user-images.githubusercontent.com/105094769/194693320-13058543-e3ba-448d-8c7a-6871298a8b44.png)

When l tried to run the helloworld example, l got the error 7.  
![image](https://user-images.githubusercontent.com/105094769/194693664-cc096a49-5f0b-4ec3-b644-bc4c52ad6083.png)

Then l found the error may be caused by the wrong directories of **_labview_grpc_server.dll_** and **_labview_grpc_generator.dll_**.  

For Code Generator, "Get ProtoParser DLL Directory.vi" gets the _labview_grpc_generator.dll_ directory like the picture(for example on Win64) below.
![image](https://user-images.githubusercontent.com/105094769/194693738-e9ff7cd1-482a-4ab6-88a4-ffa4f1ce5c55.png)
But the actual directory: (**No "Libraries" folder**)
![image](https://user-images.githubusercontent.com/105094769/194696477-bd6bcf65-ff74-4dc5-a148-663b7aaee48d.png)
For running gRPC communication, "Get Server DLL Path.vi" gets the _labview_grpc_server.dll_ directory like the picture(for example on Win64) below.
![image](https://user-images.githubusercontent.com/105094769/194693930-a83faa9a-553f-416f-a1d8-4cb60eb3b47b.png)
But the actual directory: (**No "Libraries" folder**)
![image](https://user-images.githubusercontent.com/105094769/194696459-407b5f4c-3132-46ac-b879-c33a6859c3f3.png)

**Comment by yijueli** [comment]
l once installed v0.4.9.1 and v0.5.0.1 and those Dlls were in the same paths as the ones defined in the code above like the picture below.
![image](https://user-images.githubusercontent.com/105094769/194694378-720cb8cf-2b4c-420b-8d69-ed57f5cbae01.png)  
![image](https://user-images.githubusercontent.com/105094769/194694413-22b259c7-56c8-4635-8366-2899f4057219.png)

**Comment by yijueli** [comment]
cc @gaoruhao @ericgross2

**Comment by shivaprasad-basavaraj** [comment]
Fixed in the [0.5.1.2 release](https://github.com/ni/grpc-labview/releases/tag/v0.5.1.2).
