### ISSUE TITLE
Reentrancy Settings

### ISSUE THREAD

**Issue by yijueli** [ni/grpc-labview#198]
Recently we have received the request of modifying the reentrancy of grpc client request VIs in order to improve the system performance from our customers. Request Link: https://github.com/ni/adas-replay-hil-internal/discussions/348

Among the gRPC VIs, we noticed the Client Unary Call.vim was all re-entrant.The DLL calls are also configured to support calls form multiple threads.
![image](https://user-images.githubusercontent.com/105094769/205592652-8dcb1017-4c9b-442e-8488-cae781d2378d.png)
![image](https://user-images.githubusercontent.com/105094769/205593264-c5ed299a-d509-40c0-b626-d6ca69a11bad.png)

However, the caller --Unary VIs below that were generated by the grpc scripting tool were all non-reentrant.
![image](https://user-images.githubusercontent.com/105094769/205593346-ca69ad24-8157-4a9c-bbfc-3a616e440262.png)

**Comment by ni-sujain** [comment]
@yijueli 
Initially it was mix and match where some VIs were shared clone re-entrant and some were non-reentrant. We changed some of the VIs to have Pre-allocated shared clone re-entrancy via ths PR #106 .  At that point we only changed the VI's under grpc-lvsupport.lvlib. We can certainly try to make the client template VI's re-entrant. I am not sure about the impact on memory footprint though for ADAS

**Comment by eyesonvis** [comment]
It sounds like there is no known reason why those VIs need to stay non-re-entrant. I would recommend that the ADAS team implement this change and contribute it rather than waiting for LabVIEW R&D to implement it. FYI @gregr-ni

**Comment by gregr-ni** [comment]
Agree with the no reason to stay reentrant. Sumit has already created a PR though so unless there is more to do, the ADAS team shouldn't need to do anything.

**Comment by ni-sujain** [comment]
fixed in PR #200
