### ISSUE TITLE
Not all data types are supported

### ISSUE THREAD

**Issue by ccifra** [ni/grpc-labview#20]
We should complete the support for the remaining gRPC datatypes.  This includes:
FIXED64
FIXED32
SFIXED32
SFIXED64
SINT32
SINT64

Add first class support for enums.  Currently enums are just ints.  We should create proper rings for them in LabVIEW.  Enums can be sparse and have repeated values so we will have to create rings to support all possible enums.

**Comment by Aasief-Khan** [comment]
Hi @ccifra. I am currently working on a project wherein I need to create a client with a proto file that has fixed64 and oneof datatype. Could you please let me know the tentative timeline for support of the above data types and oneof datatype?

**Comment by eyesonvis** [comment]
Support for sint32, sint64,fixed32, fixed64, sfixed32 and sfixed64 was added in release 0.5.0.1. Enum request is tracked by Issue #58, so I'm closing this Issue.
