### ISSUE TITLE
how to setup gRPC  for nirfsg with the target file from a Labview example?

### ISSUE THREAD

**Issue by markusmat97** [ni/grpc-labview#226]
I was trying to build a labview server and client for a labview example 'RFSG Arbitrary waveform.vi' and the protofile can be found in 'https://github.com/ni/grpc-device/tree/main/generated/nirfsg'
I tired to build generate grpc server and client.It was missing many RPC messages and files for server and client.

Did someone tired to generate SC for the labview VI's?Is it posible to build a gRPC for the above case?

AB#2287319

**Comment by Rohith-Grandhi** [comment]
@markusmat97, Looking at the nirfsg proto file, it looks like you are importing other proto files, have you add the right import paths in the code gen tool?

And another observation is that, the nirfsg proto file has "oneof" datatype, which is currently not supported in gRPC-LabVIEW.  one of type support is tracked in this issue: https://github.com/ni/grpc-labview/issues/21

**Comment by Rohith-Grandhi** [comment]
Observed another bug (https://github.com/ni/grpc-labview/issues/261) when trying to generate LV server and client using the rfsg proto files
