### ISSUE TITLE
Memory Leak?->Violation?

### ISSUE THREAD

**Issue by yijueli** [ni/grpc-labview#230]
Recently l encountered an issue about memory violation when making requests via gRPC in a simple Unary method. l attached the VIs [memory violation.zip](https://github.com/ni/grpc-labview/files/10790274/memory.violation.zip) and l added logic only in the Start Sync.vi and in Client.vi. The APIs used are made of LabVIEW official libraries.

- Software environment
1. Win 10
2. gRPC v1.0.0.1
3. LabVIEW 2021SP1 (more specific: 21.0.1f1/f2)

You can reproduce the issue by following the steps below:
- Steps:
1. Open Memory Violation.lvproj
![image](https://user-images.githubusercontent.com/105094769/220228836-c3638579-c727-40d0-bc87-41c92ef645ea.png)
2. Open Run Service.vi to start the gRPC server.
![image](https://user-images.githubusercontent.com/105094769/220228921-fcf20165-77c9-4ccc-8caa-8ab818736b27.png)
3. Open Client.vi to run the client.
![image](https://user-images.githubusercontent.com/105094769/220228997-a0f9b04f-4960-4db3-9576-6b45ac0c039b.png)

4. If you run the code for the first time, it will seem to be normal like the picture below.
![image](https://user-images.githubusercontent.com/105094769/220229122-885c2cec-06a3-4eda-a30e-891255ffffa1.png)

5. Then you can try to run the client again and again. You can see LabVIEW crash. Sometimes you can see the dialogue reported by LabVIEW. 
![image](https://user-images.githubusercontent.com/105094769/220231300-91a7b87e-7a41-4060-b8bd-8d14dc2b71b4.png)
The crash log and dump files are attached here: [Crash.zip](https://github.com/ni/grpc-labview/files/10789029/Crash.zip)

- Workaround:
Now l made requests via gRPC in a bidirectional streaming method which can split the arrays into strings/integers to be sent. It actually makes the code always run normally.

- Key Points:
1. The client sent a large string array(almost 3KB) to the server and got response(almost 88B) each time.
2. LabVIEW of some version did not crash but l found some values were abnormal in that situation. Therefore l thought the issue was much related to memory control.
3. There is a great possibility that the first run can run normally but the later run seems to cause LabVIEW crash. So l guess memory leak of which the size is related to message size and then it causes memory violation.

Of course l am not sure whether the issue comes from gRPC. l am not sure whether the 3KB message is not supported. Hope you guys can help to double confirm.

Thank You

**Comment by dchakrab-NI** [comment]
The crash happens after the client VI has finished running and while the VIs are being unreserved.
The crash seems to be consistently happening while un-reserving a clone of the Variant to Data Node vi in the project. Some of the clones are unreserved without any issues but one of the clone VIs will cause the crash.
While unreserving we do a bunch of cleanup. While doing this cleanup, LvVariants present in the VI are destroyed. While deleting one of these LvVariants in a clone we get the crash.

**Comment by dchakrab-NI** [comment]
I removed most of the methods and services and was able to reproduce the issue using one service and one gRPC method in the project. Here the client sends an array of strings and gets back an array of uInts. Also, the section of the code which produces the long json string is present in the client.

When the error out of the section of the code which produces the long json string is connected to the gRPC create client node's error in then we get the crash. But when the error out is not connected then the crash does not happen.

We suspected re-entrancy of the Variant to Data Node vi to be responsible for the crash so we removed some recursive code and hardcoded some values to make the vi non-reentrant but we were also able to reproduce the issue after making the vi non re-entrant.

So it seems like there is some kind of race condition introduced when the error out of the long json string producing code is connected to the gRPC open client code.

**Comment by dchakrab-NI** [comment]
I was able to reproduce the issue with a simpler input cluster having just 3-4 elements passed to the Data Container and Version to JSON vi . Even in that case the crash is happening while destroying the LvVariant during the cleanup of the Variant to Data Node vi
