### ISSUE TITLE
Error code -999

### ISSUE THREAD

**Issue by twaltersp** [ni/grpc-labview#231]
When running the gRPC server I periodically get error -999.  Sometimes this happens in the Get...Request and sometimes in the Set...Response.  

Error -999 is not listed.  
Can you provide any information on the cause of the error and suggestions on debugging?  

AB#2312183

**Comment by twaltersp** [comment]
Found the answer to my own question.  Error -999 occurs on the server when the request from a client is aborted due to a timeout on the client.  

Updating the error message to clearly communicate this would be really helpful.  Once I understood the issue I was quickly able to resolve it but I spend a number of hours trying to figure out why I was getting frequent -999 errors.

**Comment by ni-sujain** [comment]
@twaltersp on which version of grpc-labview release are you see this? can you attach an example project also to replicate this?
We are not seeing any error -999.

**Comment by ni-sujain** [comment]
This issue has been fixed in https://github.com/ni/grpc-labview/pull/197/
For client side it will show deadline exceeded , for server side it will show operation cancelled errros
