### ISSUE TITLE
Errors while trying to regenerate code after making modifications in rpc methods of a service.

### ISSUE THREAD

**Issue by yash3001** [ni/grpc-labview#244]
I came across many bugs while regenerating the code after trying out different modifications in the rpc methods of a service defined in the protofile. I will list all the bugs that I found.

### Software Environment:
1. Windows 10
2. Labview 2022Q3 (22.3.1f8)

### Original Protofile "greet.proto" (before modifications) that I used to generate the code for the first time:
```protobuf
syntax = "proto3";

package newgreeter;

service Greeter {
    rpc SayHello (HelloRequest) returns (HelloReply);
    rpc ParrotSayHello (HelloRequest) returns (stream HelloReply);
    rpc ChattyClientSayHello (stream HelloRequest) returns (DelayedReply);
    rpc InteractingHello (stream HelloRequest) returns (stream HelloReply);
}

message HelloRequest{
    string message = 1;
}

message DelayedReply{
    string message = 1;
    repeated HelloRequest request = 2;
}

message HelloReply{
    string message = 1;
}
```

### Code Generator configurations (will remain same):
![230800095-bed3e5ce-88d6-40d2-8909-d17ef3e6f263 (1)](https://user-images.githubusercontent.com/43678393/231116557-402d8adc-96e3-4ffd-8387-cc32540d6107.png)

## Following are the bugs (these are caused when I modify the protofile and then try to generate the code again:
1. ### Adding a new RPC Method - 
    
    The files for the new RPC method is not created for the client but is created for the server. However the method cannot be found in 
    the event loop of the sync.vi

    **Steps to reproduce the error:**
    1. Add a new rpc method to the protofile as follows:
        ```protobuf
        syntax = "proto3";

        package newgreeter;
        
        service Greeter {
            rpc SayHello (HelloRequest) returns (HelloReply);
            rpc ParrotSayHello (HelloRequest) returns (stream HelloReply);
            rpc ChattyClientSayHello (stream HelloRequest) returns (DelayedReply);
            rpc InteractingHello (stream HelloRequest) returns (stream HelloReply);
            rpc NewMethod (HelloRequest) returns (HelloReply);
        }
        
        message HelloRequest{
            string message = 1;
        }
        
        message DelayedReply{
            string message = 1;
            repeated HelloRequest request = 2;
        }
        
        message HelloReply{
            string message = 1;
        }
        ```

    3. Run the code generator using the same parameters.
   
    5. You will get an empty folder of the rpc method in the client library as shown below:
        ![image](https://user-images.githubusercontent.com/43678393/231018989-b65bb7a7-3f86-49d2-b9b2-cbeaf0614f09.png)
        
        But on the server side, all files are created

    6. Also the new rpc method cannot be found in the Event Structure of the "Start Sync.vi" as shown below:
        ![Capture (2)](https://user-images.githubusercontent.com/43678393/231019897-a0c9bcaa-1f4e-4c68-a1be-15b4e49e49c9.png)

3. ### Changing an existing rpc method's request or response message type -
    
    If we change the request message or the response message of method, then the following changes are not reflected upon 
    regeneration.

3. ### Renaming an existing rpc method -

    Upon renaming any rpc method and then when trying to regenerate the code, we will get Error 5010.
    ![Capture (3) (1)](https://user-images.githubusercontent.com/43678393/231021110-90f5e277-9fec-419b-8ffc-14183ae684ea.png)

    **Steps to reproduce this error:**
    
    1. Modify the protofile as follows:
        ```protobuf
        syntax = "proto3";
        
        package newgreeter;
        
        service Greeter {
            rpc SayHello (HelloRequest) returns (HelloReply);
            rpc ParrotSayHello (HelloRequest) returns (stream HelloReply);
            rpc ChattyClientSayHello (stream HelloRequest) returns (DelayedReply);
            rpc RenamedMethod (stream HelloRequest) returns (stream HelloReply);
        }
        
        message HelloRequest{
            string message = 1;
        }
        
        message DelayedReply{
            string message = 1;
            repeated HelloRequest request = 2;
        }
        
        message HelloReply{
            string message = 1;
        }
        ```

    2. Run the code generator and you will get the error.

4. ### Adding a new service -

    If we try to add a new service and then regenerate the code, then it will create empty folders for the client library but will create everything for the server library

AB#2360906

**Comment by bbanacki** [comment]
I noticed the same issue, the only workaround I know is to create a new project a and rerun the code generator each time the proto file is updated with new methods. This makes it difficult to keep up with the changes made to the service (in another language maintained by a different team)
