### ISSUE TITLE
Potential "Opened File Leakage" Issue when Running with RT

### ISSUE THREAD

**Issue by NeilChien** [ni/grpc-labview#257]
Recently we found the root cause of the crash/hang on/no response situation(running in RT) from the offering is "**Leak on the gRPC opened files**".
After a deep debugging, we found that if there not exist any delay between "Destroy.vi" and "Stop Server.vi", then causes "opened files leakage" in Linux RT.

So
1. Does this a bug?
2. Or, does there is recommanded have "time wait" between "Destroy.vi" and "Stop Server.vi"?
(After go through the BasicTutorial, I found there does not exist a wait time part between "Destroy.vi" and "Stop Server.vi" as shown in the below picture.)
![image](https://user-images.githubusercontent.com/23252005/236864848-4f8c4074-9720-4d0d-93ae-3b25f551113e.png)

Environment : 
RT System Image 2023Q1
gRPC Version 0.5.1.4

Steps:
1. Open the project I attached here
2. Connect to RT
3. Execute the "lsof Monitoring.vi, this VI would help to monitoring the amount of opened file.
![image](https://user-images.githubusercontent.com/23252005/236862341-74ced8f9-f1d7-4bf4-915a-853d5d304a7b.png)
4. Execute te "Run Service.vi" within server lib. Keep the "milliseconds  to wait" with 0.
![image](https://user-images.githubusercontent.com/23252005/236862747-a86eeadd-a07a-49fd-8702-33db980509fd.png)
5. You will see the "opened file amount" increasing with the "Repeat Times" increase.
![image](https://user-images.githubusercontent.com/23252005/236864558-393a705b-1881-4136-9c2d-be59e0b2e8b0.png)
6. Repeat the steps but set the "milliseconds to wait" to any value greater than 0, then the "opened file amount" would result in a stable amount.

[gRPC - Opened File Leakage.zip](https://github.com/ni/grpc-labview/files/11422372/gRPC.-.Opened.File.Leakage.zip)

FYI @gaoruhao 

AB#2386968

**Comment by ni-sujain** [comment]
@NeilChien  Please try with v1.0.0.4 pre-release and let us know if this issue exists. We recently fixed some bugs.

**Comment by NeilChien** [comment]
Hi @ni-sujain thanks for the update.
I will go and check with the v1.0.0.4 version whether have this issue. And will keep updating once I get progress.

**Comment by NeilChien** [comment]
Hi @ni-sujain,
I believe the necessary thing I have to do is to install the 1.0.0.4 version right?
Unfortunately, the opened file amount still increase after I updated gRPC version to 1.0.0.4 version. The problem still there.

Neil

**Comment by NeilChien** [comment]
Hi @ni-sujain 
I confirmed that 1.0.0.4 version still exists this issue even if I replace the .so within RT.
Here are the steps : 
1. Update to 1.0.0.4
2. Replace the .so within RT
3. Open the project and resolve the broken VIs with "Relink to SubVI".
4. Run the Test

**Comment by dchakrab-NI** [comment]
@NeilChien 
When we do Create Client, some anon_inode:[eventpoll] and anon_inode:[eventfd] files are created and when we do Client Unary Call some sockets are created. On doing Start Server also some similar files are created. The files created during client create and unary call are cleaned up when we call Client Destroy. Similarly, when we do Stop Server the files created during Start Server are destroyed.
If Client Destroy happens first then the client related files are destroyed first and the server files are destroyed afterwards when Server Stop runs. When there is no delay between Destroy Client and Stop Server, sometimes the Destroy Client happens after the Stop Server. In this case some of the files are not cleaned up properly. These files add up over subsequent Server starts and stops.

One way to ensure that Client Destroy happens before Stop Server would be to pass the error out of Destroy Client to Stop Server. In this case there will be no leakage even if there is no delay in between Server Destroy and Stop Server-
![image](https://github.com/ni/grpc-labview/assets/103986239/adb04f57-d2e4-4b49-8e43-3435e6ed2442)

**Comment by NeilChien** [comment]
Hi @dchakrab-NI,
So, how do we ensure this if the client comes from another where?
You know, in the typical use case, the gRPC client would be created from other systems.
Or do we have a method to check the exist connect from clients?

Neil

**Comment by nischalks** [comment]
Ruhao Gao
 spoke to Debarka Chakrabarti today. The conclusion is although the test project can reproduce the file leakage issue, it is not a recommended way to coding like this. In our ADAS real use case, it is not exactly the same as the test project. In the meanwhile, based on the recent tests, we don't see the leakages in our real cases any more.

Thus, I don't think we need any fixes and we will keep testing next week to see if everything is good. If no further leakage is found next week, you can close the bug.

**Comment by nischalks** [comment]
@NeilChien can you please close this bug if there are no further file leakages ?

**Comment by NeilChien** [comment]
Thank you for all the support.
