### ISSUE TITLE
Define enum with customized value will still generate sequential values in LabVIEW typedef

### ISSUE THREAD

**Issue by wendisong** [ni/grpc-labview#268]
Hi gRPC team, I defined the enum in proto file like this.
`enum NumberOfLanes {
    Unspecified = 0;
    One = 1;
    Two = 2;
	Four = 4; 
  }`

But the generated LabVIEW typedef is like this.
![image](https://github.com/ni/grpc-labview/assets/50438064/ad0b83dc-468a-4afd-a859-e6255edfbac4)

The expected values in LabVIEW typedef should be 0, 1, 2, 4. But the generated values are 0, 1, 2, 3. Is this expected behavior?

@gaoruhao , @yijueli, FYI

**Comment by Rohith-Grandhi** [comment]
@wendisong, this is expected behavior. Please refer to this [comment](https://github.com/ni/grpc-labview/issues/58#issuecomment-1450552931) in Issue #58

**Comment by wendisong** [comment]
@ru

> @wendisong, this is expected behavior. Please refer to this [comment](https://github.com/ni/grpc-labview/issues/58#issuecomment-1450552931) in Issue #58 for more details

@Rohith-Grandhi , OK, got it. So this is not an issue and you do not plan to change this behavior in the future, right?

**Comment by Rohith-Grandhi** [comment]
> @ru
> 
> > @wendisong, this is expected behavior. Please refer to this [comment](https://github.com/ni/grpc-labview/issues/58#issuecomment-1450552931) in Issue #58 for more details
> 
> @Rohith-Grandhi , OK, got it. So this is not an issue and you do not plan to change this behavior in the future, right?

Yes, currently there aren't any plans to change this behavior. You need not worry as mapping the enum with the actual value from proto file is handled automatically and you only need to work with enums. We have also implemented a VIs that are generated as part of code generation. Using these VIs you can get the actual value that was set in the proto file by inputting the enum and vice versa.

**Comment by wendisong** [comment]
> > @ru
> > > @wendisong, this is expected behavior. Please refer to this [comment](https://github.com/ni/grpc-labview/issues/58#issuecomment-1450552931) in Issue #58 for more details
> > 
> > 
> > @Rohith-Grandhi , OK, got it. So this is not an issue and you do not plan to change this behavior in the future, right?
> 
> Yes, currently there aren't any plans to change this behavior. You need not worry as mapping the enum with the actual value from proto file is handled automatically and you only need to work with enums. We have also implemented a VIs that are generated as part of code generation. Using these VIs you can get the actual value that was set in the proto file by inputting the enum and vice versa.

@Rohith-Grandhi , could you please point me the VI name? Or where to find the VIs? Thanks.

**Comment by Rohith-Grandhi** [comment]
@wendisong, the VIs can be found in the generated code in the same folder as the generated enum typedef. Example is shown below:
![image](https://github.com/ni/grpc-labview/assets/112845560/97db65b9-53f9-4ed3-ac78-fa037ba27c33)

**Comment by wendisong** [comment]
> @wendisong, the VIs can be found in the generated code in the same folder as the generated enum typedef. Example is shown below: ![image](https://user-images.githubusercontent.com/112845560/245044325-97db65b9-53f9-4ed3-ac78-fa037ba27c33.png)

@Rohith-Grandhi , thanks a lot.
