### ISSUE TITLE
Occasional Hang on Client Unary Call.vim

### ISSUE THREAD

**Issue by yijueli** [ni/grpc-labview#272]
grpc version: v1.0.0.5
labview 2023

Hi! Recently l found a strange hang on Client Unary Call.vim when l tested our system. You can see the hang as the picture below:
![image](https://github.com/ni/grpc-labview/assets/105094769/da9ef5c5-54e1-43a0-b7ac-1e5b01fc209c)

When l used gdb debugger to attach the process, the thread info was：
![image](https://github.com/ni/grpc-labview/assets/105094769/a79a6f82-92ed-4e6e-b31b-5c4bf98ff185)

Originally l thought the LV_Occurrence was stuck, but l found it was still running:
![image](https://github.com/ni/grpc-labview/assets/105094769/93c2d32b-b4db-44b7-9222-fc6accc100f4)

Does someone have any idea about the hang? l am not sure whether it is related to https://github.com/ni/grpc-labview/issues/207 and my previous issue(https://github.com/ni/grpc-labview/issues/217). Client Unary Call.vim seems to wait something which may be one occurrence or any other signal so that it cannot exit normally.

The hang was rare to see and hard to reproduce but we have seen it twice in the past six months on the two test machines.

AB#2438128

**Comment by AndrewHeim** [comment]
Solution is related to #193 .  I don't have a LV 2019 environment right now, but this fix works locally for me.
