### ISSUE TITLE
labview grpc as client?

### ISSUE THREAD

**Issue by ShoutangYang** [ni/grpc-labview#30]
i want python grpc as server, labview program as client,i can't find labview support client.

**Comment by ShoutangYang** [comment]
I look forward to your reply. Thank you

**Comment by navinsubramani** [comment]
Hi @ShoutangYang - Have you tried the latest release: https://github.com/ni/grpc-labview/releases

this has support for the non-streaming LabVIEW client. Would this work for you?

**Comment by ShoutangYang** [comment]
I go to try.If the communication between the Labview client and the  python server is successful. Is there any requirement for 
Python GRPC module or version?

**Comment by navinsubramani** [comment]
I don't think so. If you have a python server built already using a proto file. Then use the same .proto to create a LabVIEW client using the latest release packages. They should be able to communicate between them well.

**Comment by ccifra** [comment]
Client support has been implemented with the same datatype support as the server support.  You can do standard and streaming calls with a LabVIEW client now.  The scripting tool will let you select generation of a client API or server implementation for any proto file.
