### ISSUE TITLE
Broken MessageConverterProxy.vim is generated using the template generator

### ISSUE THREAD

**Issue by dixonjoel** [ni/grpc-labview#304]
When I generate a library from our measurement_service.proto, there is a 'MessageConverterProxy.vim' that is generated on disk, not included with the generated library. When opened, it is broken because of a missing 'package_templatemessage.ctl'. See the included image.

Steps to reproduce: Follow the steps [here](https://github.com/ni/measurementlink-labview/blob/main/docs/Regenerating%20Server%20and%20Client.md) in the 'MeasurementLink Measurement Server Internal' section to build our measurement_service.proto file.

This doesn't break the service since it's not included in the library. However, it does break our package build when we try to build the library into a .vip file.

Workaround: We've deleted the file from disk manually and that seems to fix our issue building. We would like to avoid having to do this manual step each time we generate.
![image](https://github.com/ni/grpc-labview/assets/38357562/72d9a384-5e8c-4130-97c4-8ac0392e8105)

AB#2509637

**Comment by yash-ni** [comment]
Fixed with PR #310
