### ISSUE TITLE
Generated files using LabVIEW 32 bit do not work when deploying to LinuxRT

### ISSUE THREAD

**Issue by rdecarreau** [ni/grpc-labview#318]
This bug is a little strange so I will do my best to describe the situation.

I have LabVIEW 2021Sp1 32 bit in which we have done most of our development for a server and a client application. LabVIEW 2021 on a LinuxRT target (natively 64bit) seems to work just fine, and we've used it for a long time now. I installed LabVIEW 2023 64bit IDE and updated the Target to LabVIEW 2023. If I try to deploy my application using the previously-generated grpc files in LabVIEW 2023 64bit, the application crashes lvrt; throwing a pointer reference error on the screen.

I regenerated the files using LabVIEW 2023 64 bit and all was well. The problem with that is that I would like to continue using LabVIEW 2021 for right now as our source-code and in that, I am FORCED to use 32bit as RT is not supported in LabVIEW 2021 64bit IDE. What I have had to do to keep that version of LabVIEW is generate using 2021 64bit and using those files, those seem to work fine in LabVIEW 2022 and LabVIEW 2023.

Is it expected that LabVIEW 2021 32bit-generated files would not work in LabVIEW 2022/2023 64bit? That seems odd to me and was confirmed as a little odd by the [LabVIEW User Group.](https://teams.microsoft.com/l/message/19:9ba96624423c486db14d5fa7f47b9047@thread.skype/1695995308281?tenantId=87ba1f9a-44cd-43a6-b008-6fdb45a5204e&groupId=95029edb-0859-42cd-aca6-0293aece0321&parentMessageId=1695995308281&teamName=NI%20LabVIEW%20User%20Group&channelName=General&createdTime=1695995308281)

AB#2537790

**Comment by yash-ni** [comment]
Thank you for reporting this issue. We're closing it as there has been no response from for an extended period. However, please remember that you can reopen this issue at any time if you have more information to provide or encounter the problem again in the future. We value your input and look forward to any future interaction. Thank you for your contribution.

**Comment by rdecarreau** [comment]
This version of the HPS API contains the generated gRPC files in labview 2021 32bit. I was trying to use this on LabVIEW 2023 64bit when I realized the issue. It might be challenging to use this code as-is, though. Unfortunately I was not able to get time to make a strippsed-down version of our problem in time.

https://github.com/ni/srdt-volta/releases/download/v0.1.2-rc/ni-hps-17000-client-api_0.1.2-0_windows_all.nipkg

I will leave this closed for now as we have no need to deliver LabVIEW 2021 32bit.
