### ISSUE TITLE
Which Linux distribution is the default supported one?

### ISSUE THREAD

**Issue by kwitekrac** [ni/grpc-labview#321]
I'm curious to know which Linux distribution is the default one supported by the package code. It appears that the `build_on_linux.yml` workflow is building the shared library for Ubuntu. However, when I try to install the package on Ubuntu 20.04, I encounter the following error: `Error 7, Call Library Function Node in grpc-lvsupport-release.lvlib:CreateSerializationSession.vi:5640001->Untitled 4`. I've double-checked the permissions, so that shouldn't be the issue. Interestingly, when I replace the default .so file with the shared library built using CMake, it works as expected.

**Comment by yash-ni** [comment]
Hello @kwitekrac, we're executing Linux workflows using the 'ubuntu-latest' environment in GitHub Actions. At the moment, 'ubuntu-latest' is set as the default for Ubuntu version 22.04. For a comprehensive list of the installed software and their respective versions in 'ubuntu-latest,' you can refer to this link: [ubuntu-latest](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md)
