### ISSUE TITLE
grpc-labview client call hangs even though the server responded.

### ISSUE THREAD

**Issue by rdecarreau** [ni/grpc-labview#324]
We have an application in which we can replicate a client-side hang of the grpc-labview binary. We are almost positive (still gathering data) that the server replied, and we have configured the grpc-labview timeout on the client. What can we do to gather information while the hang is happening? What can I do to help someone take a look?

AB#2576440

**Comment by rdecarreau** [comment]
LabVIEW 2023 Q3
cRIO RT Target on 23Q3
grpc-labview 1.0.0.5 and 1.0.0.8

**Comment by rdecarreau** [comment]
I have a VI which can replicate but since we have to run it in our lab, I will need to work with someone who can help.

**Comment by AndrewHeim** [comment]
This sounds similar to my problem I had today - #193 was behind it.  Try ruling that out and see if it helps?

I don't have a LV 2019 environment to do it with right now, or I'd already have submitted the pull request.

**Comment by rdecarreau** [comment]
Hahahah. That was our team. Wow. Yes very much related and is what I did as a workaround.

**Comment by nischalks** [comment]
This is now fixed in this release of https://github.com/ni/grpc-labview/releases/tag/v1.2.1.1, please confirm if the hang goes away with this release.
