### ISSUE TITLE
gRPC Server halted by invalid Enum received from Client

### ISSUE THREAD

**Issue by BShermanator** [ni/grpc-labview#328]
If a user sends an enum of 0 indicating it is unspecified, a gRPC server is halted by a modal error window. 

I do not think this is expected since there is comment, saying we do not want the server to stop.

![image](https://github.com/ni/grpc-labview/assets/98476085/5db44465-1b61-4808-a2c7-062ed42c765d)

AB#2597172

**Comment by pratheekshasn** [comment]
@BShermanator
The set of values in the enum _must_ contain a 0 (according to the documentation [here](https://protobuf.dev/programming-guides/proto3/#enum)). The error you have mentioned above gets thrown only when the user passes a value that is not defined in the proto file with which the client/server code is generated.

Could you please attach a project from which I can reproduce this issue?

**Comment by BShermanator** [comment]
@pratheekshasn - I was aware of an enum containing 0, but my understanding that the error case occurred if I sent 0 was incorrect. The new insight is helpful because I must be sending a number other than 0. 

However, if a client does send an enum that is not define in the proto file, the LV gRPC server stops because of the modal error dialog. The error should be handled in a way that does not halt the servers execution. Do you agree or is there another piece of information I am missing?

**Comment by pratheekshasn** [comment]
Yes, I agree. I have created a PR for this issue.

**Comment by pratheekshasn** [comment]
This has been fixed by PR #334. Closing this issue.
