### ISSUE TITLE
LabVIEW crash | Running two service on same address

### ISSUE THREAD

**Issue by navinsubramani** [ni/grpc-labview#35]
When two LabVIEW service is run on a same address (machine and port number), then LabVIEW crashes.

**Comment by dixonjoel** [comment]
It seems to me we need to fix the crash plus modify the template code to either generate itself with a unique port number or pick a unique port number at runtime. Probably the latter is necessary.

**Comment by navinsubramani** [comment]
If it picks a unique port number during run time, then folks need something like discovery service or else they might need to run the client by manually changing the new port every time :)

Until discovery service becomes public too, we have to keep the default behaviour to use the fixed port?
