### ISSUE TITLE
Wait On Occurrence Wrapper.vi should be re-entrant. Currently causes hang in our app

### ISSUE THREAD

**Issue by NIbbuchanan** [ni/grpc-labview#354]
vi.lib\gRPC\LabVIEW gRPC Library\Shared\Wait On Occurrence Wrapper.vi has a few issues:
- It is not marked as re-entrant/in place so if a grpc call takes awhile, it blocks other calls from going through.
- The separate compiled code flag is not checked, which is annoying when going between different contexts (ie. windows an RT) and this VI has to be saved each time.  Use the same settings as the Wait on Occurence.vi it calls.

Our app (FlexLogger) was hanging because of this and when I changed this VI to be re-entrant/in-place, it worked again.

**Comment by yash-ni** [comment]
Hi @NIbbuchanan, sorry for the late reply. We will be releasing the export next week.

**Comment by ni-sujain** [comment]
@NIbbuchanan the export is now available here https://github.com/ni/grpc-labview/releases/tag/v1.2.3.1
