### ISSUE TITLE
LabVIEW Crashes when Stopping Two Parallel Running gRPC Servers (on Windows and on NI Linux RT)

### ISSUE THREAD

**Issue by gmkrtchy** [ni/grpc-labview#361]
Hi,

 We are developing a solution as part of a TBU CCS project that incorporates ni gRPC. In simple terms, we have multiple modules that will have a server setup inside the module & we will be connecting clients from teststand to be able to communicate directly with these modules. These modules will be within a overriding application and running within NI LINUX RT.
 
We have come across an issue whereby multiple servers is causing NI RT and also Labivew on windows to crash. We do not believe we are doing anything out of the ordinary and we are doing something similar to the TBU SRD ReplayHiLAD RT application, of whcih we can see doesn't do anything "non-standard". 

As an example we created one Simple LV project consists of 2 Modules
 
![image](https://github.com/ni/grpc-labview/assets/106306776/db487a73-ed94-4201-a1c4-5ad8af841585)
![image](https://github.com/ni/grpc-labview/assets/106306776/e29cf226-207f-4518-9ac8-13e5493f13cb)

Both Servers has the same  code, after 30 seconds each server generates "Server Stop" event which stops the gRPC Loop.
I see that Module1 Server Stops properly, but during stopping Module 2 it loses the connection to the target (See screenshot below)

![image](https://github.com/ni/grpc-labview/assets/106306776/38d52986-95a4-4396-831b-dbd9af174b96)
![image](https://github.com/ni/grpc-labview/assets/106306776/fb552fc5-0a5c-46ca-8ece-2912214320c5)

We are using these versions of gRPC packages
![image](https://github.com/ni/grpc-labview/assets/106306776/9e6345b4-da39-4f78-8db5-ea21e03867f7)

There looks to be a similar ticket already created **[here](https://github.com/ni/grpc-labview/issues/356)** from a partner. Any help and advice on this topic is appreciated as this is a solution required for a key NI Customer
Please Find attached the LV Project with Protos
[gRPC_MultiServer.zip](https://github.com/ni/grpc-labview/files/15506004/gRPC_MultiServer.zip)

AB#2759169

**Comment by nischalks** [comment]
@gmkrtchy, we will look into this issue.

**Comment by j-medland** [comment]
This is a very rough guess and I am no C++ programmer but is it because `LVProtoServerReflectionPlugin` is being deleted here? 

Looking at how the plugin is instantiated and stored I believe it would be shared between both server instances.

https://github.com/ni/grpc-labview/blob/add68a662437536ee76ecc64cc6a6d469625dea4/src/grpc_server.cc#L273
