### ISSUE TITLE
Missing labview_grpc_generator.dll in Load ProtoFile.vi

### ISSUE THREAD

**Issue by DaliaR1** [ni/grpc-labview#375]
I want to generate code from a proto file. 
There is a nice tool called **Open gRPC Server-Client [2] - Code Generator.vi**. 
I ran it from the folder \\grpc-labview-master\labview source\Client Server Support New\gRPC Scripting Tools

![PrototoVI](https://github.com/user-attachments/assets/95c8be5f-c248-46f2-9967-692e11a164bf)

When I run it (I specified the proto file and target project), it gives me error: 
`Error 7 occurred at Call Library Function Node in gRPC Template Creation Utility.lvlib:Load ProtoFile.vi`

Looking at the Load ProtoFile.vi, it looks for a DLL called Libraries\Win64\**labview_grpc_generator.dll**
I couldn't find it in the code. 
Where is this dll?

Thanks 
Dalia

AB#2834397

**Comment by yash-ni** [comment]
Hi @DaliaR1, did you follow the instructions to install the gprc-labview package as specified in the [README](https://github.com/ni/grpc-labview/blob/master/docs/QuickStart.md#labview-grpc)?

**Comment by Jul-ctrl** [comment]
Hello,

I have the same problem, I followed the instructions step by step but the dll doesn't exist on my computer.
My LabVIEW version is 2019 SP1 32 bits and I use the last GRPC Library version 
If you have any ideas on how to solve this problem 
Thanks in advance

Jules

**Comment by DaliaR1** [comment]
Hi @yash-ni 

Im sorry for the late response. 
I followed the instructions from the Readme: 
1. Download and Unzip grpc-labview.zip which contains the released packages.
2. Install the following gRPC package:
ni_lib_labview_grpc_library-x.x.x.x.vip
ni_lib_labview_grpc_servicer-x.x.x.x.vip
ni_lib_grpc_server_and_client_template[2]-x.x.x.x.vip

Unfortunately, there none of them install the labview_grpc_generator.dll. 

I will try to reproduce it in a different computer, but I already tried twice in 2 different computers. 

Which package should install the labview_grpc_generator.dll?

Thank you

**Comment by DaliaR1** [comment]
Hi @yash-ni 

Do I need to build [Building the Scripting and Server binaries](https://github.com/ni/grpc-labview/blob/master/docs/Building.md) to use Labview scripting tool? 
Im a little confused where is the labview_grpc_generator.dll and which vip install it. 

Waiting for your answer. 
Thanks you
Dalia

**Comment by DaliaR1** [comment]
Hi @Jul-ctrl 

I found the solution.
The correct GRPC VIP packages are here:
[https://github.com/ni/grpc-labview/releases]

Download the grpc-labview.zip from the Assets. It includes 3 VIP packages. The ni_lib_grpc_server_and_client_template[2]-x.x.x.x.vip installs the dll and the code generator.
![image](https://github.com/user-attachments/assets/a09e3190-a884-4f54-b16b-1acede594d80)

Hope it will help you
Dalia
