### ISSUE TITLE
Nested clusters get jumbled from service to client

### ISSUE THREAD

**Issue by BrandtSwanson** [ni/grpc-labview#378]
There is an issue when populating a response with repeated messages. array_0 should have 1,2,3,4 and array_1 should have 5,6,7,8, but all the data ends up in array 0.

Here is the proto file:
![Proto](https://github.com/user-attachments/assets/3918dae6-a7e2-43d0-96f8-2c958fa38b79)

Here you can see how the response is populated:
![GetStatus](https://github.com/user-attachments/assets/47b59380-26a1-45b0-acbd-e613df094a30)

Here is how the response shows up on the client side:
![Response](https://github.com/user-attachments/assets/47971d05-6d85-430f-9472-23ebfd65b4ba)

AB#2842884

**Comment by jasonmreding** [comment]
Setting `EfficientMessageCopy = FALSE` in `feature_config.ini` will avoid this problem until bugs in the "efficient" code path can be fixed.

**Comment by jasonmreding** [comment]
This should be fixed in #387
