### ISSUE TITLE
GetUnpackedField.vim crashes when trying to retrieve a boolean array.

### ISSUE THREAD

**Issue by ccaltagi** [ni/grpc-labview#388]
I created a Measurement Plugin service that produces a boolean array.
When I try to retrieve the field using GetUnpackedField.vim after starting the service and running it, LabVIEW crashes.
I am attaching the code of the service and vi to reproduce the crash: Crash Boolean Array Out.vi
[MeasurementLink Bug.zip](https://github.com/user-attachments/files/17197238/MeasurementLink.Bug.zip)

AB#2884139

**Comment by nischalks** [comment]
Hi @ccaltagi, if you have a fix please go ahead and raise a PR, we can review it and try and help you make a release if its critical for measurement link.

cc @jasonmreding @yash-ni
