### ISSUE TITLE
Send error details from service to client in LabVIEW

### ISSUE THREAD

**Issue by navinsubramani** [ni/grpc-labview#44]
When the business logic of the service has an error (say an instrument error), then this should be propagated to the client. Looks like the service by default has the capability to send status for each call. If the best practice is to use that, then in LabVIEW we need a capability to send the error wire details to the client using status information.

It will be good to handle this in the service/client gRPC API layer like how LabVIEW does normally.

Note:
https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto

**Comment by navinsubramani** [comment]
@ccifra  I assume you need to handle this in C code?

**Comment by navinsubramani** [comment]
@ccifra  This is a request where "when a error in logic like instrument input value out of range", these should be passed to client.

**Comment by a-clucker** [comment]
I'll add support for this, especially "the service by default has the capability to send [gRPC] status for each call. If the best practice is to use that, then in LabVIEW we need a capability to send the error wire details". 

We ran a small test where we specifically took down the server, and the LabVIEW client call times out yet reports no error. The corresponding error we see from gRPC in our cpp endpoint and a 3rd party grpc testing tool is "14 UNAVAILABLE: failed to connect to all addresses". Our expectation is LabVIEW would also report the gRPC error, with a similar, if not exactly the same, message.

**Comment by ccifra** [comment]
Client calls will now correctly return any gRPC status errors that happen.
There is a new Set Call Status VI which the server can use to indicate an error from the diagram.  This will propagate to the client.
There is still more work to do for errors, but I think this is enough to close the issue.
