### ISSUE TITLE
Bug in Dependency for LabVIEW packages

### ISSUE THREAD

**Issue by navinsubramani** [ni/grpc-labview#57]
- Version numbers should be updated to the least supported version of dependent packages.
- New Server  & Client package should be dependent on the grpc servicer.

**Comment by eyesonvis** [comment]
@ccifra - can this Issue be closed?

**Comment by abahetik** [comment]
@navinsubramani @eyesonvis This issue has been fixed in v0.4.8.4 + . I am closing the issue
