### ISSUE TITLE
Create a Enum RPC message

### ISSUE THREAD

**Issue by navinsubramani** [ni/grpc-labview#58]
- Currently Enums are treated as a number for the gRPC communication which is fine. But it will be good to create atleast the "Enum" from proto file as a "Enum" typedef during the scripting. This will be helpful for the non gRPC communication operations.

Currently, I am creating a Enum typedef based on proto after scripting.

**Comment by drjdpowell** [comment]
I think you should allow the user to choose either a ring or an enum.  Although an enum is not always possible, it is much better than a ring.

**Comment by Rohith-Grandhi** [comment]
Listing down some of Enum features as defined in Proto3 and if they can be supported with LabVIEW Ring or Enum
| Enum features as defined in proto 3 | LabVIEW Ring| LabVIEW Enum|
| ----------- | ----------- |  -----------|
|must contain a constant that maps to Zero as its value | Yes| Yes|
|use enum type declared in one message as the type of a field in a different message| Yes | Yes |
|Enum value must be in the range of 32-bit integer| Yes | No |
| Non sequential values| No (can workaround?) | No (can workaround?)|
| Aliases - Same value to different enum constants| No | No |
|Reserved Values - The proto buff compiler will complain if any future users try to use the identifiers specified as Reserved| No| No|
||||

**Comment by eyesonvis** [comment]
We're planning to implement this feature using LabVIEW Enums. This means that users will have to call a look-up function get the numeric value for an enum item.

**Comment by drjdpowell** [comment]
>This means that users will have to call a look-up function get the numeric value for an enum item.

Sorry, what does this mean?   LabVIEW Enums are already numbers, so what is this look-up?

**Comment by drjdpowell** [comment]
Ah, so it would only be if teh User actually needed the numeric value that they would need to use this look up.

**Comment by Rohith-Grandhi** [comment]
Support for Enum type is now present in [Version 1.0.0.2 release ](https://github.com/ni/grpc-labview/releases/tag/v1.0.0.2)
