### ISSUE TITLE
Crash at Server Creation

### ISSUE THREAD

**Issue by UvQtcYZJuD7J5VW7** [ni/grpc-labview#62]
Hi everyone,

When I try to generate a server with project and proto files from _helloworld_ example, LabVIEW crash every time.

**LabVIEW version : 2021
grpc-labview version : 0.4.6.1**

I open example project (_helloworld.lvproj_)
I execute gRPC tool (tools > gRPC > open gRPC Server-Client [2] - Code Generator)

- First cell of the array, I pick proto file from example (_helloworld.proto_)
- Target Project select current and opening project (_helloworld.lvproj_)
- No Target Name
- "_hw_" as Generated Library Name

First, I generate gRPC Client : it works correctly !
Next, I try to generate gRPC Server : doesn't work.

The first time, LabVIEW crashes with this message :
![Capture](https://user-images.githubusercontent.com/90563484/150106506-1549a568-eb62-43ef-b53a-836a897986ad.JPG)

The second time, LabVIEW doesn't crash but report an error code (1305)
![Capture2](https://user-images.githubusercontent.com/90563484/150106817-908a660a-1fd2-47a5-b80f-5151bb8013e6.JPG)

I click on Continue and I search where the program crashes.
CTRL+T on gRPC Code Generator and check step by step each diagram block (and following the path given by the error code)
Found that error 1305 generated by _Get Case Structure Frame (by Name).vi_
![Capture3](https://user-images.githubusercontent.com/90563484/150107928-e6c6d031-3f66-4d01-ae53-9841babee3f5.JPG)

So, I tried another version of grpc-labview (v0.4.0). They doesn't work (crash appear in Update Methods Registration.vi with error code 1055).

According to NI Support (https://knowledge.ni.com/KnowledgeArticleDetails?id=kA00Z0000019L75SAE&l=fr-FR), error appear each time where there is Default if Unwired tunnel in structure condition.

Finally, I tried to uninstall gRPC Server and Client Template [2] to install gRPC Server and Client Template.
This time, gRPC Client work again and gRPC Server crash with 1055 error code.
![Capture4](https://user-images.githubusercontent.com/90563484/150109576-79150f2a-2364-4b1d-84bc-c542160aa0f4.JPG)

Please, let me know if you need more information.

Thanks

**Comment by navinsubramani** [comment]
Further looking at the image, this VI get's the reference to the case by name. But the case names are different for 'Default' in the image. I assume because of the language difference, this VI was not able to find a case with 'No Error' name and errors out.
![image](https://user-images.githubusercontent.com/17029551/150129432-8bde853d-0419-4b26-976c-a23fd81d46f8.png)

cc. @ccifra

**Comment by UvQtcYZJuD7J5VW7** [comment]
Everything seems to work fine. The problem was the IDE language. Thank you!
