### ISSUE TITLE
Server - Run Service.vi run one time

### ISSUE THREAD

**Issue by UvQtcYZJuD7J5VW7** [ni/grpc-labview#64]
Hi,

I try to execute the generated Server vi with default parameters (localhost:50051 / Async) and when I click on run button, the vi execute one time and stop immediately.
I download few grpc-labview version (0.3.3 to 0.4.6) and _labview_grpc_server.dll_ is present only in 0.3.3. Maybe I need to copy this DLL somewhere in my project or generate new library following [Building.md](https://github.com/ni/grpc-labview/blob/master/docs/Building.md).
I attach the vi execution : 
![Capture](https://user-images.githubusercontent.com/90563484/150301546-7b59c993-323f-499f-88d4-6d27c48c40a1.JPG)

Thanks

**Comment by UvQtcYZJuD7J5VW7** [comment]
Ok, now I understand where is my library file (_C:\Program Files (x86)\NI\LV2021\vi.lib\gRPC\gRPC Library\..._) but I can't explain why my server is run one time whereas in this [demonstration of GLA Summit](https://youtu.be/0FN9W9tzKaA?t=2171), the Server vi stay in while loop

**Comment by navinsubramani** [comment]
Hi - There is one step that you want to do to run your service. Please find the documentation under the `Starting the Server` : https://github.com/ni/grpc-labview/blob/master/docs/BasicsTutorial.md#starting-the-server

You need to replace the parent class serviceBase object with your `ServiceObject` to run it. Current it is running with the base class and thats why it stops immediately.
