### ISSUE TITLE
Error attempting to build binaries on Windows

### ISSUE THREAD

**Issue by Troy-K** [ni/grpc-labview#7]
@ccifra  Attempting to build binaries on Windows results in error as follows.
When running the command: cmake -A Win32 ..
fatal error C1083: Cannot open include file: 'pthread.h'

Looks like it is trying to include linux specific header file.
Is there any other way to test this on Windows 10?

**Comment by ccifra** [comment]
Are you building from a Visual Studio command prompt.  Windows builds should work on a system with Visual Studio installed.

**Comment by ccifra** [comment]
Closing since building on windows is known to work and I did not receive any followup.
