### ISSUE TITLE
gRPC Client Connectivity State

### ISSUE THREAD

**Issue by BShermanator** [ni/grpc-labview#70]
Is there a way to see the Client Connectivity? I can run my Client Code with no active servers and no errors are returned. We create a gRPC Channel but I do not see a way for me to query the state. Therefore, regardless if I have a valid IP address or active server or not, no errors or flags are produced.

For additional context, I am not a gRPC expert by any means.

The only thing I was able to find was information about the gRPC Connectivity API. My end goal is to see if I have an active connection to a server. Am I missing something in the current code base or is this something that could be added?

gRPC Connectivity Semantics and API
https://grpc.github.io/grpc/core/md_doc_connectivity-semantics-and-api.html

**Comment by eyesonvis** [comment]
Suggest you use a health checking protocol such as: https://github.com/grpc/grpc/blob/master/doc/health-checking.md
