### ISSUE TITLE
Importing other proto definitions inside proto file

### ISSUE THREAD

**Issue by ImreSzebelledi** [ni/grpc-labview#73]
Hello there,

It seems to me that the import keyword is not supported yet for the proto file parsing. Is this something which is already considered to be done or I just have to create one big proto file from the linked proto files? I was trying to import the proto file for Opentelemetry and as it is separated into multiple proto file so it did not work. 

Thank you in advance!

-Imre

**Comment by ccifra** [comment]
You should be able to import proto files into another proto file, but right now we don't support search paths so you must put any imported files next to the main proto file in a path that matches how you are importing the .proto file.
