### ISSUE TITLE
Make Get Server DLL Path.vi PPL compatible

### ISSUE THREAD

**Issue by sr33-multics** [ni/grpc-labview#75]
When built in to PPLs the [Get Server DLL Path.vi](https://github.com/ni/grpc-labview/blob/master/labview%20source/gRPC%20lv%20Support/Server%20API/Server/Get%20Server%20DLL%20Path.vi) does not resolve the dll path correctly.
A case structure similar to this would help resolve it.
![ppl](https://user-images.githubusercontent.com/29126754/160279669-106faa17-5a82-4dbc-ab08-70c1cc89be4c.png)

**Comment by NIbbuchanan** [comment]
I would vote for not using custom lookup paths and use the default search location LV already has for finding DLLs and shared libraries so the Call Library Function can just use labview_grpc_server.*. This makes the install a little trickier than just putting all the DLLs in a Libraries folder. On windows, it should go under LabVIEW/resource folder (use the correct 32/64-bit depending on which LV they install to. We could keep them in the libraries folder so it's easy for the user to find them and copy to other targets as needed, but CLF should not take a path and should instead use the default LV search path...like all our other driver DLLs do.

**Comment by pakdev** [comment]
Copied your idea into #164, which is now merged - thanks! This issue can now be closed

**Comment by shivaprasad-basavaraj** [comment]
The fix is part of the [0.5.1.2 release](https://github.com/ni/grpc-labview/releases/tag/v0.5.1.2).
