### ISSUE TITLE
Need Timeout in Client Calls

### ISSUE THREAD

**Issue by becega** [ni/grpc-labview#76]
When doing calls to the server, if the function is partially implemented (there is an event handle structure but it doesn't return the value). The client waits forever, hanging the application. We need to specify a timeout for how long we can wait for the query to complete.

**Comment by BShermanator** [comment]
I have an open PR already for your suggestions. I ran into the same issue. 

https://github.com/ni/grpc-labview/pull/74

**Comment by ni-sujain** [comment]
fixed by #98
