### ISSUE TITLE
Servicer build failed. @

### ISSUE THREAD

**Issue by lklsh** [ni/grpc-labview#80]
@gaoruhao  在最新的版本中，在build servicer时失败了。
1. 打开 LabVIEW gRPC Servicer.vipb 生成 vip文件出现以下问题，提示错误信息如下；想咨询一下，是哪里的配置有问题吗？
![image](https://user-images.githubusercontent.com/54324769/167249222-bd447a69-7b84-442e-8c14-05a8a111103d.png)

**Comment by ni-sujain** [comment]
I have some questions

- at what point we are getting this, I this while publishing the vi's via VIPM.
- if yes which version of VIPM are you using

**Comment by ni-sujain** [comment]
@gaoruhao is this issue related to [Bump LabVIEW gRPC Library vipb bulid spec version](https://github.com/ni/grpc-labview/pull/81)?

**Comment by abahetik** [comment]
@lklsh There was an issue in release v0.4.7.1. This has been resolved in [release v0.4.9.1](https://github.com/ni/grpc-labview/releases/tag/v0.4.9.1). Thus, I am closing this issue
