### ISSUE TITLE
Error Generating New Libraries

### ISSUE THREAD

**Issue by JamesMc86** [ni/grpc-labview#84]
I attempted to create a new client/server in LabVIEW but get the following error when running the generator:

![image](https://user-images.githubusercontent.com/4404192/167699456-e91ff646-18d3-4ba8-8145-cbbbf01e298d.png)

Steps followed:

1. Install the 0.4.7.1 release to LV 2021 SP1 32 bit
2. Copied the contents of the greeter service from the quickstart to a .proto file.
3. Ran the generator targeting a new empty project.
4. Recieved the error above.

Here is the configuration I ran:

![image](https://user-images.githubusercontent.com/4404192/167701027-cbf1b0cb-00bd-4509-9840-f1bf9ef456a9.png)

**Comment by amcclint** [comment]
I have this error when generating new libraries as well.

**Comment by abahetik** [comment]
@JamesMc86 @amcclint This issue has been fixed in [Release v0.4.9.1](https://github.com/ni/grpc-labview/releases/tag/v0.4.9.1). Thus, I am closing the issue.
