### ISSUE TITLE
LabVIEW hangs when calling the MetaDataRegistration

### ISSUE THREAD

**Issue by lucywang-NI** [ni/grpc-labview#85]
<img width="677" alt="image" src="https://user-images.githubusercontent.com/33818852/169186688-3a812e9b-640c-4dee-8b0f-f8b3f5a3590d.png">

I'm trying to use the tool to generate the grpc client code from this proto file and make it work with my grpc server which is built with Java. 
And find out calling the Create Client.vi hangs. Then I looked into the code and find the hang is at the CallFunctionNode in the MetadataRegistration.vi 

Since it get stuck in the create client code, it's reproducible even without the grpc server. 

I attached the proto file (have to rename it to .txt file for uploading)
[PdxTest.txt](https://github.com/ni/grpc-labview/files/8722923/PdxTest.txt)

**Comment by ni-sujain** [comment]
I will look into this

**Comment by ni-sujain** [comment]
@lucywang-NI  Can you try it now, we had several fixes over last month

**Comment by lucywang-NI** [comment]
I tried it and it works now. Thanks!
