### ISSUE TITLE
Bidirectional Streaming RouteGuide Test.vi Issue

### ISSUE THREAD

**Issue by gmkrtchy** [ni/grpc-labview#86]
After running Bidirectional Streaming RouteGuide Test.vi example from, Labview often crashes or throws an error.
The logic of the server contains these two sequential "not" boolean functions on the error wire of "Get Input" API which connects to "Streeming?(f)" input of the "Set output" API. (see picture below)

![image](https://user-images.githubusercontent.com/106306776/170453284-68e69a08-073a-4218-9b98-c97b86cb6066.png)

After deleting one of the boolean "Not" functions,

![image](https://user-images.githubusercontent.com/106306776/170452841-fd8c39e7-1810-4d13-9342-0f04794b9bf5.png)

 the server and client started to generate and receive data without crashing LV.
However, it shows another issue when I stopped the Client, code got stacked on "Call End" API, which is calling dll.

![image](https://user-images.githubusercontent.com/106306776/170452930-55d62232-220d-438d-8fe1-5614fb5cbdcc.png)

![image](https://user-images.githubusercontent.com/106306776/170452981-1e311d1f-a12f-4e10-8e22-bbd2d097f2f0.png)

**Comment by ni-sujain** [comment]
I have started looking at this, I will also check for the problems in Linux binaries as well

**Comment by eatondan** [comment]
Is there any update on this? I am running into the same problem when trying to do a bi-directional stream.

Thank you for your work on tihs!

**Comment by ni-sujain** [comment]
@eatondan We are still are trying to find a solution for this. Meanwhile you can use Client Cancel.vi

https://github.com/ni/grpc-labview/blob/master/labview%20source/gRPC%20lv%20Support/Client%20API/Client%20Cancel%20Call.vi

to avoid hangs. I guess it should available in the latest release

**Comment by ni-sujain** [comment]
fixed by #148
