### ISSUE TITLE
Latest release seems to have the wrong version number

### ISSUE THREAD

**Issue by neilpate** [ni/grpc-labview#88]
Is it missing a leading zero?

![image](https://user-images.githubusercontent.com/7802334/171637692-8596477e-4b08-4077-a6a1-47f8419abda2.png)

**Comment by gregr-ni** [comment]
The tag was incorrectly named. It has been fixed but has the side effect of making the 0.4.7.1 release show up at the top of the list. This will be less of an issue after the next release is created.
