### ISSUE TITLE
Typo "Streeming" instead of "Streaming" 

### ISSUE THREAD

**Issue by wheeller123** [ni/grpc-labview#89]
The set messages generated from Labview have a boolean called "Streeming". Presumably this should be "Streaming" ?

![image](https://user-images.githubusercontent.com/1076573/173053106-b8c3d056-fb14-44e1-ad94-2413ef81371f.png)

**Comment by joerghampel** [comment]
Looking at v0.4.8.2, this Control is still named "Streeming?".

<img width="557" alt="Bildschirmfoto 2022-08-17 um 15 47 23" src="https://user-images.githubusercontent.com/7075830/185150548-e8750d0f-6656-46d3-ab8a-b2e0085a373b.png">
