### ISSUE TITLE
helloworld.proto Server stops immediately 

### ISSUE THREAD

**Issue by Bas-vE** [ni/grpc-labview#91]
After testing the hello world example I tried creating a server and client from the helloworld.proto file. but for some reason the server stop immediately after starting the vi. 

I have tried to see what the difference is in comparsion with the example code, but I could not see what is happening. I have not altered the code after the tool created the code from the proto file.

For some reason the close event gets called.

**Comment by eyesonvis** [comment]
The scripted Run Service.vi passes the base class Service object to Instantiate. You need to replace the constant with your service. For the helloworld.proto file example, you'd want the Greeter class.
